Updated to V11 and evaluation plan
Open-Systems-Pharmacology/Furosemide-Model pull request #3
Opened 2024-10-15 15:09 UTC by mgsc1020

2024-10-15 15:14 UTC, mgsc1020 commented
please review @PavelBal

2024-12-23 13:38 UTC, Yuri05 commented
Observed data assignments are missing in simulations
![grafik](https://github.com/user-attachments/assets/1163814b-ab01-443e-8507-054a7861da0d)

2024-12-23 13:57 UTC, Yuri05 commented
Author name use differently across the report: _Andreansen_ vs. _Andreasen_

2025-01-06 11:59 UTC, Yuri05 commented on Evaluation/Input/Content/GOF_diagnostics.md
> +Below you find the goodness-of-fit visual diagnostic plots for the PBPK model performance of all data used presented in [Section 2.2.2](#222-clinical-data).
Still the old crossref...

2025-01-06 12:00 UTC, Yuri05 commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +### Automated Parameter Identification <a id="model-parameters-and-assumptions-absorption"></a>
the anchor "model-parameters-and-assumptions-absorption" was used 4 times, but it must be unique

2025-01-24 13:55 UTC, PavelBal commented
Remove the process OATP1B1 from the mode. @mgsc1020

2025-01-24 16:57 UTC, PavelBal commented
Figure 3-4 displays fraction excreted to feces, and figure 3-13 displays fraction absorbed. Both curves should be removed as no observed data area available.

2025-01-24 16:58 UTC, PavelBal requested changes

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/evaluation_plan.json
> +            "Path": "../../Furosemide-Model.json",
Change to "https://raw.githubusercontent.com/mgsc1020/Furosemide-Model/refs/heads/main/Furosemide-Model.json" for now.

@Yuri05 I always forget how to do it properly... the URL should point to the release but the release is not created yet..

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section1_Introduction.md
> +The herein presented model was developed and published by Hanke et al. [Britz 2020](#5-references) and adjusted later on to PK-Sim V11 by re-optimizing OAT3 and ABCC4 Kcat.
Hanke et al. but then "Britz"?

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section1_Introduction.md
> +Furosemide is a loop diuretic, and its primary mechanism of action involves inhibition of tubular re-absorption of sodium and chloride in the kidneys, specifically by blocking the sodium-chloride-pot
```suggestion
Furosemide is a loop diuretic, and its primary mechanism of action involves inhibition of tubular re-absorption of sodium and chloride in the kidneys, specifically by blocking the sodium-chloride-potassium transporter system in the thick ascending limb of the loop of Henle ([Ponto and Schoenwald 1990](#5-references)). Furosemide is used to treat edema or high blood pressure.
```

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section2.1_Modeling_Strategy.md
> +A mean model was built based on clinical data from studies with intravenous and oral administration of furosemide. The studies reported individual or mean plasma concentrations of furosemide, from wh
```suggestion
A mean model was built based on clinical data from studies with intravenous and oral administration of furosemide. The studies reported individual or mean plasma concentrations of furosemide, from which 27 studies reported fraction excreted unchanged in urine profiles following intravenous and oral administration. In the intravenous studies, furosemide was administered in doses of 20–80 mg. In the oral studies, furosemide was administered in doses of 1–80 mg. The PBPK models were built based on data from healthy individuals, using the reported sex, ethnicity and mean values for age, weight and height from each study protocol. If no demographic information was reported in the respective clinical study, a default mean individual was used with the following properties: male, European, 30 years of age, 73 kg body weight and 176 cm body height. The relative tissue-specific expressions of the enzyme and transporter predominantly being involved in the metabolism/transport of furosemide (UGT1A9, OAT3, ABCC4) were considered ([Meyer 2012](#5-references)). A Weibull function was fitted to describe the oral dissolution of furosemide.  
```

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section2.1_Modeling_Strategy.md
> +A specific set of parameters ([Section 2.3.4.](#model-parameters-and-assumptions-absorption-identification)) were optimized to describe the disposition of furosemide using the Parameter Identificatio
```suggestion
A specific set of parameters ([Section 2.3.4.](#model-parameters-and-assumptions-absorption-identification)) was optimized to describe the disposition of furosemide using the Parameter Identification module provided in PK-Sim®. To limit the parameters to be optimized during model building, the minimal number of processes necessary to mechanistically describe the pharmacokinetics and drug-drug interactions (DDIs) of the modeled drugs were implemented into the models. The furosemide OAT1 and OAT3 transport rate constants would be highly correlated in a model parameter optimization since there is no further information found to distinguish these two transporters. To avoid indentifiability issues, renal uptake of furosemide was implemented by the transporter with the slightly higher affinity for the respective substrate (OAT3) was implemented, to describe a transport that probably is accomplished by both transporters *in vivo*. Structural model selection was mainly guided by visual inspection, mean relative deviation and geometric mean fold error of all predicted AUClast and Cmax values.
```

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section2.1_Modeling_Strategy.md
> +A specific set of parameters ([Section 2.3.4.](#model-parameters-and-assumptions-absorption-identification)) were optimized to describe the disposition of furosemide using the Parameter Identificatio
> To avoid indentifiability issues, renal uptake of furosemide was implemented by the transporter with the slightly higher affinity for the respective substrate (OAT3) was implemented, to describe a transport that probably is accomplished by both transporters *in vivo*.

Very weir (and not easily understandable) wording.

2025-01-24 16:58 UTC, PavelBal commented on Evaluation/Input/Content/Section2.3_Model_Parameters_and_Assumptions.md
> +And several transport protein was implemented into the model via Michaelis-Menten kinetics
```suggestion
The following transport proteins are implemented into the model via Michaelis-Menten kinetics 
```

2025-01-30 11:11 UTC, Yuri05 commented on Evaluation/Input/evaluation_plan.json
> +            "Path": "../../Furosemide-Model.json",
@PavelBal The URL `"../../Furosemide-Model.json"` is correct and may not be changed.
It is only when referring to a project **outside** the current repository - then it must refer to a released version
Would be something like this then:
`"https://raw.githubusercontent.com/Open-Systems-Pharmacology/Verapamil-Model/v2.0/Verapamil-Model.json"`

2025-03-24 16:17 UTC, PavelBal approved these changes

2025-03-24 16:18 UTC, PavelBal commented
@Yuri05 Good to go.

2025-04-07 09:22 UTC, merged